### ISSUE TITLE
bug: sponsorblock fails when building

### ISSUE THREAD

**Issue by nnaem** [revanced/revanced-patcher#107]
### Type

Crash

### Bug description

I tried to build revanced, all jars included and integrations

### Steps to reproduce

Attempt to build revanced with the sponsorblock patch

### Relevant log output

```shell
[builder] SEVERE: sponsorblock failed:
[builder] app.revanced.patcher.patch.PatchResultError
[builder] at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:331) at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47) at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.lang.NullPointerException
[builder] at app.revanced.patches.youtube.layout.sponsorblock.bytecode.patch.SponsorBlockBytecodePatch.execute(SponsorBlockBytecodePatch.kt:329) at app.revanced.patches.youtube.layout.sponsorblock.bytecode.patch.SponsorBlockBytecodePatch.execute(SponsorBlockBytecodePatch.kt:41) at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326) ... 16 more
```

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
SponsorBlock is currently incompatible with older versions of the app, please use the latest one until it's back ported to the last version of Android 7.

**Comment by nnaem** [comment]
I have the latest version of YouTube and revanced, and my Android version is 11.

**Comment by oSumAtrIX** [comment]
Please record the issue from the beginning, when patching the app until the error occurs.

**Comment by oSumAtrIX** [comment]
Wrong place for this issue.

**Comment by nnaem** [comment]
> Wrong place for this issue.

In patches repo?
