### ISSUE TITLE
Patcher Crash on "Compiling resources"

### ISSUE THREAD

**Issue by AlphaGaming7780** [revanced/revanced-patcher#155]
### Type

Crash

### Bug description

Hello, 
every time I try to patch an app, it fails, regardless of the patch or the apps, it crashes all the time and with the same error all the time.

I post Patcher Log when I try on tiktok version 27.8.3

### Steps to reproduce

Try to patch a app on xiaomi maybe, or on android 12,...

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied disable-login-requirement
Applied downloads
Applied feed-filter
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Applied predictive-back-gesture
Applied remove-screenshot-restriction
Applied settings
Applied show-seekbar
Applied sim-spoof
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~ScAW3sFafMTbhSB8t7vtBw==/app.revanced.manager.flutter-MYIXFYC_tQpzGoqkSzzwdg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-LYVEZG/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-LYVEZG/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:365)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:144)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~ScAW3sFafMTbhSB8t7vtBw==/app.revanced.manager.flutter-MYIXFYC_tQpzGoqkSzzwdg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-LYVEZG/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-LYVEZG/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:361)
	... 6 more
```

### Additional context

About section of the Manager :
Version: 0.0.54
Model: Mi 10
Android Version: 12
Arch: arm64-v8a

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Apply the recommended set of patches.
