### ISSUE TITLE
Tiktok patching failed

### ISSUE THREAD

**Issue by m7md7essen** [revanced/revanced-patcher#157]
### Type

Crash

### Bug description

Tiktok patching failed

### Steps to reproduce

1.download tiktok app v 27.8.3 from apkmirror
2.select the app 
3.patch it with all patches

### Relevant log output

```shell
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~m695fZOdaBIbpdlensITAw==/app.revanced.manager.flutter-59Y9_Wh1BOw1z5dqRPu4kQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RCDAIL/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RCDAIL/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:365)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:144)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~m695fZOdaBIbpdlensITAw==/app.revanced.manager.flutter-59Y9_Wh1BOw1z5dqRPu4kQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RCDAIL/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RCDAIL/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:361)
	... 6 more
```

### Screenshots or videos

![Screenshot_2023-02-10-09-27-37-923_app revanced manager flutter](https://user-images.githubusercontent.com/32914068/218029852-896cfcfc-01e1-4f2a-b7bd-e5539b140bca.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Select the recommended patches.
