### ISSUE TITLE
bug: Failed merging integration in Youtube from APK

### ISSUE THREAD

**Issue by MonoS** [revanced/revanced-patcher#182]
### Type

Other

### Bug description

When generating a patched version of youtube it seems to fail to merge integration subsequently failing to apply a lot of different patched

### Steps to reproduce

Uninstalled and Reinstalled Revanced Manager
Download YT official APK from the link on the reddit guide
Open Revanced Manager and select the YT APK and import patch selection
Patch fails

Tried on two different phone
One Plus 5 Rooter with Android AICP 12
Samsung Z Flip 3 SM-F711B non rooted with stock Android 13

### Relevant log output

```shell
One Plus 5
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Failed to apply client-spoof: 'client-spoof' depends on 'spoof-signature-verification' but the following error was raised: 'spoof-signature-verification' depends on 'integrations' but the following error was raised: Could not find hook target fingerprint.
Failed to apply copy-video-url: 'copy-video-url' depends on 'copy-video-url-resource' but the following error was raised: 'copy-video-url-resource' depends on 'settings' but the following error was raised: 'settings' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Applied custom-branding
Failed to apply disable-fullscreen-panels: 'disable-fullscreen-panels' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply disable-player-popup-panels: 'disable-player-popup-panels' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply disable-zoom-haptics: 'disable-zoom-haptics' depends on 'settings' but the following error was raised: 'settings' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply downloads: 'downloads' depends on 'downloads-resource-patch' but the following error was raised: 'downloads-resource-patch' depends on 'settings' but the following error was raised: 'settings' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hdr-auto-brightness: 'hdr-auto-brightness' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-ads: 'hide-ads' depends on 'HideAdsResourcePatch' but the following error was raised: 'HideAdsResourcePatch' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-autoplay-button: 'hide-autoplay-button' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-breaking-news-shelf: 'hide-breaking-news-shelf' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-crowdfunding-box: 'hide-crowdfunding-box' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-email-address: 'hide-email-address' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-get-premium: 'hide-get-premium' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-player-overlay: 'hide-player-overlay' depends on 'HidePlayerOverlayResourcePatch' but the following error was raised: 'HidePlayerOverlayResourcePatch' depends on 'settings' but the following error was raised: 'settings' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-watch-in-vr: 'hide-watch-in-vr' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-watermark: 'hide-watermark' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply minimized-playback: 'minimized-playback' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply old-quality-layout: 'old-quality-layout' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Applied open-links-externally
Applied premium-heading
Failed to apply remember-video-quality: 'remember-video-quality' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Applied remove-player-button-background
Applied remove-screenshot-restriction
Failed to apply return-youtube-dislike: 'return-youtube-dislike' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply seekbar-tapping: 'seekbar-tapping' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply sponsorblock: 'sponsorblock' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply spoof-app-version: 'spoof-app-version' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply tablet-mini-player: 'tablet-mini-player' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply theme: 'theme' depends on 'SeekbarColorBytecodePatch' but the following error was raised: 'SeekbarColorBytecodePatch' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply vanced-microg-support: 'vanced-microg-support' depends on 'hide-cast-button' but the following error was raised: 'hide-cast-button' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply video-ads: 'video-ads' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply wide-searchbar: 'wide-searchbar' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
An error occurred! Aborting
Error:
java.lang.NullPointerException: Attempt to invoke interface method 'org.w3c.dom.Node org.w3c.dom.NamedNodeMap.getNamedItem(java.lang.String)' on a null object reference
	at app.revanced.patches.youtube.misc.settings.resource.patch.SettingsResourcePatch.close(SettingsResourcePatch.kt:166)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:363)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:920)







Samsung Z Flip

Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Failed to apply client-spoof: 'client-spoof' depends on 'spoof-signature-verification' but the following error was raised: 'spoof-signature-verification' depends on 'integrations' but the following error was raised: Could not find hook target fingerprint.
Failed to apply copy-video-url: 'copy-video-url' depends on 'copy-video-url-resource' but the following error was raised: 'copy-video-url-resource' depends on 'settings' but the following error was raised: 'settings' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Applied custom-branding
Failed to apply disable-fullscreen-panels: 'disable-fullscreen-panels' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply disable-player-popup-panels: 'disable-player-popup-panels' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply disable-zoom-haptics: 'disable-zoom-haptics' depends on 'settings' but the following error was raised: 'settings' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply downloads: 'downloads' depends on 'downloads-resource-patch' but the following error was raised: 'downloads-resource-patch' depends on 'settings' but the following error was raised: 'settings' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hdr-auto-brightness: 'hdr-auto-brightness' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-ads: 'hide-ads' depends on 'HideAdsResourcePatch' but the following error was raised: 'HideAdsResourcePatch' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-autoplay-button: 'hide-autoplay-button' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-breaking-news-shelf: 'hide-breaking-news-shelf' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-crowdfunding-box: 'hide-crowdfunding-box' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-email-address: 'hide-email-address' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-get-premium: 'hide-get-premium' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-player-overlay: 'hide-player-overlay' depends on 'HidePlayerOverlayResourcePatch' but the following error was raised: 'HidePlayerOverlayResourcePatch' depends on 'settings' but the following error was raised: 'settings' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-watch-in-vr: 'hide-watch-in-vr' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply hide-watermark: 'hide-watermark' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply minimized-playback: 'minimized-playback' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply old-quality-layout: 'old-quality-layout' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Applied open-links-externally
Failed to apply premium-heading: The file /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JDAKQG/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png does not exist in the resources. Therefore, this patch can not succeed.
Failed to apply remember-video-quality: 'remember-video-quality' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Applied remove-player-button-background
Applied remove-screenshot-restriction
Failed to apply return-youtube-dislike: 'return-youtube-dislike' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply seekbar-tapping: 'seekbar-tapping' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply sponsorblock: 'sponsorblock' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply spoof-app-version: 'spoof-app-version' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply tablet-mini-player: 'tablet-mini-player' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply theme: 'theme' depends on 'SeekbarColorBytecodePatch' but the following error was raised: 'SeekbarColorBytecodePatch' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply vanced-microg-support: 'vanced-microg-support' depends on 'hide-cast-button' but the following error was raised: 'hide-cast-button' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply video-ads: 'video-ads' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Failed to apply wide-searchbar: 'wide-searchbar' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not a patcher issue

**Comment by MonoS** [comment]
> This is not a patcher issue

My apologies for filling it in the wrong section, where should i fill it? Should it go in Integration then?

**Comment by oSumAtrIX** [comment]
No, you are likely patching a version that is not supported. ReVanced Manager has warned you.

**Comment by MonoS** [comment]
But current and suggested are the same version
![Screenshot_20230528-204511_ReVanced Manager](https://github.com/revanced/revanced-patcher/assets/801011/b042b007-7020-4e21-b664-e255c9170817)

 also i checked the hash with the version linked on the reddit's guide and it's the same 
![image](https://github.com/revanced/revanced-patcher/assets/801011/b7988465-ce21-4eef-84d1-b7e0d8d4fe9d)

**Comment by oSumAtrIX** [comment]
![IMG_20230528_205400](https://github.com/revanced/revanced-patcher/assets/13122796/9c1b4804-de83-469f-a661-aef38a6e467e)
Follow these steps

**Comment by MonoS** [comment]
Thank you for those instruction, i didn't thought about uninstalling the installed YT version as i was patching from the APK, but why should it error if the installed and the currently patching APK are different?

**Comment by oSumAtrIX** [comment]
I don't know what you did, so I can't answer your question.

**Comment by Visne** [comment]
I also get this error (`Could not find hook target fingerprint.`). I have re-installed ReVanced Manager completely, I have re-installed Youtube completely, I am using the recommended version (v18.19.35), and latest ReVanced manager version (1.3.5). Patches are also up to date.
