### ISSUE TITLE
Revanced Extended patcher aborting patch process

### ISSUE THREAD

**Issue by yurisilpess** [revanced/revanced-patcher#197]
### Type

Crash

### Bug description

Whenever I attempt to patch Youtube (I have only tried youtube since it's revanced extended) it's stuck for around a minute or two before aborting. The normal manager's patcher does not abort.

**Patches Chosen**
Bypass Ambient Mode Restrictions (v0.0.1)
Custom Branding Icon Mmt (v0.0.1)
Disable Startup Shorts Player (v0.0.1)
Enable External Browser (v0.0.1)
Enable Minimized Playback (v0.0.1)
Enable Open Links Directly (v0.0.1)
Enable Tablet Miniplayer (v0.0.1)
Force Premium Heading (v0.0.1)
Hide Autoplay Button (v0.0.1)
Hide Email Address (v0.0.1)
Hide Floating Microphone (v0.0.1)
Hide General Ads (v0.0.1)
Hide Mix Playlists (v0.0.1)
Hide Video Ads (v0.0.1)
Materialyou (v0.0.1)
MicroG Support (v0.0.1)
Optimize Resource (v0.0.1)
Overlay Buttons (v0.0.1)
Protobuf Spoof (v0.0.1)
Return Youtube Dislike (v0.0.1)
Sponsorblock (v0.0.1)

Device: Samsung Galaxy S10e
Android version: 12 (OneUI 4.1)
Revanced manager version: 1.3.6
Youtube version: 18.25.39 (I have tried with the version 18.17.43, the suggested version, and even older suggested ones, got the same error.)

### Steps to reproduce

1. Download the recommended (or the latest) YouTube APK
2. Open the Manager
3. Select the right APK
4. Choose the patches
5. Wait for the patcher to do its thing
It's Revanced Extended, so: [Revanced Extended Guide for Beginners](https://www.reddit.com/r/revancedextended/comments/12vxggr/revanced_extended_guide_for_beginners/)

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
An error occurred! Aborted
Error:
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:316)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:306)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:306)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/Integer;Ljava/lang/Iterable;Ljava/lang/Iterable;Ljava/lang/Iterable;Lkotlin/jvm/functions/Function1;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprint; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprint' appears in base.apk)
	at app.revanced.patches.shared.patch.integrations.AbstractIntegrationsPatch$IntegrationsFingerprint.<init>(AbstractIntegrationsPatch.kt:32)
	at app.revanced.patches.shared.patch.integrations.AbstractIntegrationsPatch$IntegrationsFingerprint.<init>(AbstractIntegrationsPatch.kt:28)
	at app.revanced.patches.youtube.misc.integrations.fingerprints.InitFingerprint.<init>(InitFingerprint.kt:5)
	at app.revanced.patches.youtube.misc.integrations.fingerprints.InitFingerprint.<clinit>(Unknown Source:2)
	at app.revanced.patches.youtube.misc.integrations.patch.IntegrationsPatch.<init>(IntegrationsPatch.kt:15)
	... 13 more
```

### Screenshots or videos

https://github.com/revanced/revanced-manager/assets/99032447/22bef919-7678-4dd4-85b8-3e4da84643fe

Skip to 22 sec

### Additional context

At first I got a split-app error, so the only way for the patching to work was if I chose the apk from my storage. After uninstalling updates for Youtube, it didn't give that error. Then I tried again, and it aborted again; note that the separately downloaded apks were also not working. I tried disabling Youtube and tried with the installed apks (not bundle). I have uninstalled and reinstalled revanced manager, nothing. I checked and I have MicroG chosen as a patch. I need all the help I can get.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Julius8900** [comment]
We don't offer support for ReVanced Extended.
