### ISSUE TITLE
Spotify 8.8.62.491 force close with latest patcher 

### ISSUE THREAD

**Issue by edzamber** [ReVanced/revanced-patcher#216]
### Type

Crash

### Bug description

Spotify can't be launched, it force close. 

### Steps to reproduce

Patch with command line and with Revanced manager 

### Relevant log output

```shell
FATAL EXCEPTION: main
Process: com.spotify.music:playcore_missing_splits_activity, PID: 16656
java.lang.RuntimeException: Unable to create application com.spotify.music.SpotifyApplication: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object p.c8n.get()' on a null object reference
	at android.app.ActivityThread.handleBindApplication(Unknown Source:1119)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:855)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:173)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:331)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object p.c8n.get()' on a null object reference
	at com.spotify.music.SpotifyApplication.onCreate(SourceFile:159)
	at android.app.Instrumentation.callApplicationOnCreate(Unknown Source:0)
	at android.app.ActivityThread.handleBindApplication(Unknown Source:982)
	... 9 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not a patcher issue, something in your patching or installation process is wrong
