### ISSUE TITLE
Tiktok Compiling Sources Error

### ISSUE THREAD

**Issue by m7md7essen** [ReVanced/revanced-patcher#227]
### Type

Crash

### Bug description

Tiktok Compiling Sources Error

### Steps to reproduce

1- Download Tiktok 30.6.4
2- Select Default Patches
3- Patch

### Relevant log output

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Disable login requirement succeeded
Downloads succeeded
Feed filter succeeded
Fix google login succeeded
Hide ads succeeded
Playback speed succeeded
Settings succeeded
Show seekbar succeeded
Compiling modified dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 404000 free bytes and 394KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:112)
	at com.android.tools.smali.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java:270)
	at com.android.tools.smali.dexlib2.dexbacked.DexReader.readString(DexReader.java:610)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:336)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:329)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:372)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:367)
	at com.android.tools.smali.dexlib2.dexbacked.reference.DexBackedMethodReference$1.readItem(DexBackedMethodReference.java:82)
	at com.android.tools.smali.dexlib2.dexbacked.reference.DexBackedMethodReference$1.readItem(DexBackedMethodReference.java:78)
	at com.android.tools.smali.dexlib2.dexbacked.util.FixedSizeList.get(FixedSizeList.java:46)
	at java.util.AbstractList$Itr.next(AbstractList.java:371)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
	at java.util.AbstractList.equals(AbstractList.java:547)
	at com.android.tools.smali.util.CharSequenceUtils.listEquals(CharSequenceUtils.java:47)
	at com.android.tools.smali.dexlib2.base.reference.BaseMethodReference.equals(BaseMethodReference.java:58)
	at java.util.HashMap.getNode(HashMap.java:571)
	at java.util.LinkedHashMap.get(LinkedHashMap.java:464)
	at com.android.tools.smali.dexlib2.writer.pool.BaseIndexPool.getItemIndex(BaseIndexPool.java:52)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.getReferenceIndex(InstructionWriter.java:596)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.getReferenceIndex(InstructionWriter.java:582)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:433)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1361)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1115)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:415)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:370)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:158)
	at lanchon.multidexlib2.DexIO.access$000(DexIO.java:38)
	at lanchon.multidexlib2.DexIO$1.call(DexIO.java:99)
	at lanchon.multidexlib2.DexIO$1.call(DexIO.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

### Screenshots or videos

![Screenshot_2023-08-29-08-50-34-479_app revanced manager flutter](https://github.com/ReVanced/revanced-patcher/assets/32914068/1cffc585-f841-4117-8467-88ac50184837)
![Screenshot_2023-08-29-08-50-42-552_app revanced manager flutter](https://github.com/ReVanced/revanced-patcher/assets/32914068/edaff042-8b15-4935-abe8-6bdeb2256f74)
![Screenshot_2023-08-29-08-50-46-430_app revanced manager flutter](https://github.com/ReVanced/revanced-patcher/assets/32914068/8c7fdbff-45ab-47c0-9000-9f883c8b1a59)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Ushie** [comment]
Duplicate of https://github.com/ReVanced/revanced-patcher/issues/193
