### ISSUE TITLE
bug: patching on android 8 is no longer possible

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-patcher#230]
### Type

Crash

### Bug description

Starting with ReVanced Patcher v14, it's not possible to patch on an Android 8 device

### Steps to reproduce

1. Be on Android 8
2. Attempt to patch anything on ReVanced Manager

### Relevant log output

```shell
APK
Reading APK
Decoding app manifest
Loading patches
An error occurred:
java.lang.NullPointerException
	at java.io.File.<init>(File.java:282)
	at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
	at app.revanced.patcher.PatchBundleLoader$Dex.<init>(PatchBundleLoader.kt:60)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$13(MainActivity.kt:184)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$6dokpIuPm1kqn7qLA9JtiVzSCi0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:784)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Ushie** [comment]
I just realized that v14.2.2 fixed this, closing as completed
