### ISSUE TITLE
Revanced is broken

### ISSUE THREAD

**Issue by NotRabug50** [ReVanced/revanced-patcher#233]
### Type

Crash

### Bug description

I just inject modules to youtube app

### Steps to reproduce

Opened Revanced
Select youtube apk file
And patch

### Relevant log output

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Custom player overlay opacity succeeded
Disable zoom haptics succeeded
Enable debugging succeeded
Enable tablet layout succeeded
Hide cast button succeeded
Premium heading succeeded
Theme succeeded
Compiling modified dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/~~XlitKz5wNvKbeRaMM3Tqow==/app.revanced.manager.flutter-EwUB1Pec8o74M8f_r3F3uA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-APSXWF/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1539698112, --version-name, 18.34.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3712417802157941361.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-APSXWF/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-APSXWF/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-APSXWF/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
	at app.revanced.patcher.Patcher.get(Patcher.kt:232)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$13(MainActivity.kt:244)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$6dokpIuPm1kqn7qLA9JtiVzSCi0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/~~XlitKz5wNvKbeRaMM3Tqow==/app.revanced.manager.flutter-EwUB1Pec8o74M8f_r3F3uA==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-APSXWF/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1539698112, --version-name, 18.34.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3712417802157941361.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-APSXWF/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-APSXWF/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-APSXWF/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Insufficient reproduction steps.
