### ISSUE TITLE
When I try to patch the youtube app apk and I am useing the suggested apk version it says in youtube revanced and when I patch it and the logs are in the Relevant copy output

### ISSUE THREAD

**Issue by AveryGameing3445-tech** [ReVanced/revanced-patcher#255]
### Type

Other

### Bug description

I found it when I downloaded the suggested youtube apk version 18.38.44 that youtube revanced suggested

### Steps to reproduce

Download the suggested youtube apk version 18.38.44 that youtube revanced suggested  from uptodown.com and select all of the default patches except for Remove player controls background

### Relevant log output

```shell
~ Device Info
ReVanced Manager: 1.12.1
Build: release
Model: SM-T220
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi

~ Patch Info
App: com.google.android.youtube v18.38.44
Patches version: v2.194.0
Patches: Alternative thumbnails, Always autorepeat, Bypass URL redirects, Client spoof, Comments, Copy video url, Custom branding, Custom player overlay opacity, Disable Shorts on startup, Disable auto captions, Disable fine scrubbing gesture, Disable player popup panels, Disable zoom haptics, Enable debugging, Enable tablet layout, External downloads, HDR auto brightness, Hide 'Load more' button, Hide Shorts components, Hide ads, Hide album cards, Hide autoplay button, Hide breaking news shelf, Hide captions button, Hide cast button, Hide crowdfunding box, Hide email address, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Hide info cards, Hide layout components, Hide player buttons, Hide seekbar, Hide timestamp, Hide video action buttons, Hide watermark, Minimized playback, Navigation buttons, Old video quality menu, Open links externally, Playback speed, Player flyout menu, Premium heading, Remember video quality, Return YouTube Dislike, Seekbar tapping, SponsorBlock, Spoof app version, Swipe controls, Tablet mini player, Theme, Vanced MicroG support, Video ads, Wide searchbar

~ Settings
Enabled changing patches: true
Enabled universal patches: true
Enabled experimental patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

~ Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
An error occurred:
brut.androlib.exceptions.AndrolibException: Could not generate: values-v27/styles.xml
	at brut.androlib.res.ResourcesDecoder.generateValuesFile(ResourcesDecoder.java:223)
	at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:182)
	at app.revanced.patcher.data.ResourceContext.decodeResources$revanced_patcher(ResourceContext.kt:50)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:194)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:286)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$30(MainActivity.kt:285)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$nWp6SJoHVIOkEmiKbEEka4nn7Ag(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.directory.DirectoryException: file must be a directory: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WZNKKV/cache/res/values-v27
	at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
	at brut.directory.FileDirectory.createDirLocal(FileDirectory.java:64)
	at brut.directory.AbstractDirectory.createDir(AbstractDirectory.java:149)
	at brut.directory.AbstractDirectory.getFileOutput(AbstractDirectory.java:122)
	at brut.androlib.res.ResourcesDecoder.generateValuesFile(ResourcesDecoder.java:205)
	... 20 more
```
```


### Screenshots or videos

![Screenshot_20231014_210812_ReVanced Manager](https://github.com/ReVanced/revanced-patcher/assets/146142928/e18c0c85-90f3-4f3b-9df9-c1580eda5565)
![Screenshot_20231014_210829_ReVanced Manager](https://github.com/ReVanced/revanced-patcher/assets/146142928/2f48d2d5-da2b-4a59-9ce4-f39a56b01234)
![Screenshot_20231014_210839_ReVanced Manager](https://github.com/ReVanced/revanced-patcher/assets/146142928/9fb23d2a-f5d6-438f-b850-cddb76d29402)


### Solution

_No response_

### Additional context

I don't really have any additional context here sorry :(

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not a patcher issue, but ReVanced Manager

**Comment by AveryGameing3445-tech** [comment]
> This is not a patcher issue, but ReVanced Manager

Ok so is there a way to fix this?

**Comment by AveryGameing3445-tech** [comment]
> This is not a patcher issue, but ReVanced Manager

Should I just reinstall ReVanced Manager?
