### ISSUE TITLE
bug: Reddit patch install failure

### ISSUE THREAD

**Issue by lenny1596** [ReVanced/revanced-patcher#294]
### Bug description

the patching fails just after compiling the dex files.
Steps to reproduce bug:
1. select reddit latest apk from storage
2. click on patch
3. process starts, however just after compiling the dex files you will notice failure.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: RMX1921
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.reddit.frontpage v2024.18.0 (Suggested: Any)
Patches version: v4.7.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 4 patches
Compiling patched dex files
Compiled 13 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Su6NODtScbgriXOzEFpw9g==/app.revanced.manager.flutter-5UWh9pqZPLKOOf4CEQbIAQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWFKRJ/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1577901, --version-name, 2024.18.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6339844648738751695.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWFKRJ/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWFKRJ/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWFKRJ/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:923)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Su6NODtScbgriXOzEFpw9g==/app.revanced.manager.flutter-5UWh9pqZPLKOOf4CEQbIAQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWFKRJ/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1577901, --version-name, 2024.18.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6339844648738751695.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWFKRJ/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWFKRJ/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RWFKRJ/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
```

### Additional context

This is my first time reporting bugs in github. I tried mentioning as much as I could. I hope you can make sense from it. I really love revanced community for making existing applications better.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The bug report belongs in revanced-patches and exists there already.
