### ISSUE TITLE
Compilation Youtube Revanced bugged

### ISSUE THREAD

**Issue by edzamber** [revanced/revanced-patcher#97]
### Type

Other

### Bug description

Compilation failed because missing method : NoClassDefFoundError: app/revanced/patcher/patch/OptionsContainer

### Steps to reproduce

Compil with patcher on ubuntu

### Relevant log output

```shell
INFOS: Skipping enable-debugging: Not explicitly included 
INFOS: swipe-controls succeeded 
INFOS: downloads succeeded 
INFOS: seekbar-tapping succeeded 
INFOS: amoled succeeded 
INFOS: disable-create-button succeeded 
INFOS: hide-cast-button succeeded 
INFOS: return-youtube-dislike succeeded 
INFOS: hide-autoplay-button succeeded 
INFOS: premium-heading succeeded 
Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/patch/OptionsContainer
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at app.revanced.patches.youtube.layout.branding.icon.patch.CustomBrandingPatch.<clinit>(CustomBrandingPatch.kt)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:236)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:546)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:496)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:284)
	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:44)
	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:325)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.OptionsContainer
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 36 more
```

**Comment by SebiAi** [comment]
Have the same error message with the following versions (all downloaded from the releases)

**Versions:**
*YT:* 17.33.42
*Patches:* revanced-patches-2.50.6.jar
*CLI:* revanced-cli-2.9.5-all.jar
*Integrations:* app-release-unsigned.apk - v0.36.5
*OS:* Ubuntu 20.04.5 LTS x86_64 (Kernel: 5.4.0-125-generic)
*Java:*
```
openjdk 17.0.4.1 2022-08-12 LTS
OpenJDK Runtime Environment Zulu17.36+17-CA (build 17.0.4.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu17.36+17-CA (build 17.0.4.1+1-LTS, mixed mode, sharing)
```

**How to reproduce:**
1. Download patches, cli, integrations and yt apk
2. Try to patch: `java -jar revanced-cli-2.9.5-all.jar -a youtube.apk -b revanced-patches-2.50.6.jar -o ReVanced.apk -m app-release-unsigned.apk`
3. Error :(

**Comment by Canny1913** [comment]
> Have the same error message with the following versions (all downloaded from the releases)
> 
> **Versions:** _YT:_ 17.33.42 _Patches:_ revanced-patches-2.50.6.jar _CLI:_ revanced-cli-2.9.5-all.jar _Integrations:_ app-release-unsigned.apk - v0.36.5 _OS:_ Ubuntu 20.04.5 LTS x86_64 (Kernel: 5.4.0-125-generic) _Java:_
> 
> ```
> openjdk 17.0.4.1 2022-08-12 LTS
> OpenJDK Runtime Environment Zulu17.36+17-CA (build 17.0.4.1+1-LTS)
> OpenJDK 64-Bit Server VM Zulu17.36+17-CA (build 17.0.4.1+1-LTS, mixed mode, sharing)
> ```
> 
> **How to reproduce:**
> 
> 1. Download patches, cli, integrations and yt apk
> 2. Try to patch: `java -jar revanced-cli-2.9.5-all.jar -a youtube.apk -b revanced-patches-2.50.6.jar -o ReVanced.apk -m app-release-unsigned.apk`
> 3. Error :(

CLI is broken at the moment.

**Comment by Canny1913** [comment]
@SebiAi Try again with latest versions. It should be fixed now.

**Comment by SebiAi** [comment]
Thank you @Canny1913 , it is working now!
You guys are awesome! Props to the whole developer team! :heart:

**Comment by edzamber** [comment]
> @SebiAi @edzamber Try again with latest versions. It should be fixed now.

Perfect, many thanks its fixed !

Good job bro

**Comment by edzamber** [comment]
> @SebiAi @edzamber Try again with latest versions. It should be fixed now.

Perfect, its fixed !

Many thanks, good job bro
